table data_dictionary
	lineageTag: fe7b0644-fc91-4289-94c2-8a580eca738e

	column Table
		dataType: string
		lineageTag: d33ebeda-8b3a-4a61-b589-1cb561559e05
		summarizeBy: none
		sourceColumn: Table

		annotation SummarizationSetBy = Automatic

	column Field
		dataType: string
		lineageTag: 864cb391-f8b3-486f-ab8e-2726ef96842b
		summarizeBy: none
		sourceColumn: Field

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 7d335344-fcd1-4bb4-b000-32f3351459f8
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition data_dictionary = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Utente\Desktop\CRM+Sales+Opportunities\data_dictionary.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Table", type text}, {"Field", type text}, {"Description", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

