table DimDate
	lineageTag: 231fb0e9-8e4d-441f-b803-32fa66c9c1bb

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 01772f8f-52ba-4feb-95d8-496a854a8885
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: f404924a-d24c-4b84-ad65-f223922d1922
			defaultHierarchy: LocalDateTable_412342f9-a71a-45ad-b4c1-5e1e2f40f121.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 199fcb8e-c750-4608-b4e1-4bd33cbf5114
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: dd510f5b-211e-4687-b6b3-87450f37b367
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterID
		dataType: string
		lineageTag: c3c1d29d-2fd0-4b6a-bb33-997eb5c28edd
		summarizeBy: none
		sourceColumn: QuarterID

		annotation SummarizationSetBy = Automatic

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: fd465805-44d5-484b-9ed4-94a3893628c0
		summarizeBy: sum
		sourceColumn: MonthNum

		annotation SummarizationSetBy = Automatic

	column MonthID
		dataType: string
		lineageTag: 0163fd66-f834-4e5c-ae1e-b39540f8ff79
		summarizeBy: none
		sourceColumn: MonthID

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ecd22f35-6f3c-4293-8520-069b28e711cf
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 53c2c7b9-afd6-47a0-a757-8a14aa0f56b6
		summarizeBy: sum
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column DayofWeek
		dataType: int64
		formatString: 0
		lineageTag: 03b1ce24-0970-4199-ab44-2cc7b444a6a7
		summarizeBy: sum
		sourceColumn: DayofWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 592ec851-c023-4885-95c2-27a7abe95581
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source = ```
				let    
				    StartDate = #date(2019,01,01),
				    EndDate = #date(2021,12,31),
				    Source = {Number.From(StartDate)..Number.From(EndDate)},
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Year", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Added QuarterID" = Table.AddColumn(#"Inserted Quarter", "QuarterID", each Text.From([Year]) & "Q" & Text.From([Quarter]), type text),
				    #"Inserted Month" = Table.AddColumn(#"Added QuarterID", "MonthNum", each Date.Month([Date]), Int64.Type),
				    #"Added MonthID" = Table.AddColumn(#"Inserted Month", "MonthID", each Text.From([Year]) & Text.PadStart(Text.From([MonthNum]), 2, "0"), type text), 
				    #"Inserted MonthName" = Table.AddColumn(#"Added MonthID", "MonthName", each Text.Start(Date.MonthName([Date]), 3), type text),
				    #"Inserted DayOfMonth" = Table.AddColumn(#"Inserted MonthName", "DayOfMonth", each Date.Day([Date]), Int64.Type),
				    #"Inserted DayOfWeek" = Table.AddColumn(#"Inserted DayOfMonth", "DayofWeek", each Date.DayOfWeek([Date]), Int64.Type),
				    #"Inserted DayName" = Table.AddColumn(#"Inserted DayOfWeek", "DayName", each Date.DayOfWeekName([Date]), type text)
				in
				    #"Inserted DayName"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

