table 'Sales Opportunities'
	lineageTag: 440ccf02-eadb-47c7-8242-746496dd7b3d

	column 'Reporting Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ca9986d3-bbbd-4ae2-a313-0d461c711a26
		summarizeBy: none
		sourceColumn: Reporting Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Salesperson
		dataType: string
		lineageTag: 12ea7d01-e8a9-4d82-ba47-616e6346b13d
		summarizeBy: none
		sourceColumn: Salesperson

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: 6a9e85b7-7628-46a1-9f0a-4e6afd5bae21
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 2863eab4-0d3d-4d17-92d3-ebd78c338ace
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Sales stage'
		dataType: string
		lineageTag: d4ef6541-f6d5-4b22-948a-3ce00d8cf2f1
		summarizeBy: none
		sourceColumn: Sales stage

		annotation SummarizationSetBy = Automatic

	column 'Opportunity ID'
		dataType: string
		lineageTag: 523538e0-bd76-4257-8c4e-9f6e92292b71
		summarizeBy: none
		sourceColumn: Opportunity ID

		annotation SummarizationSetBy = Automatic

	column 'Opportunity Value (USD)'
		dataType: int64
		formatString: 0
		lineageTag: 2790a408-04ab-4b4f-8efc-e13def827ca0
		summarizeBy: sum
		sourceColumn: Opportunity Value (USD)

		annotation SummarizationSetBy = Automatic

	column 'Sales Channel'
		dataType: string
		lineageTag: 40755c0e-c107-440f-8c20-1f50fbadc0aa
		summarizeBy: none
		sourceColumn: Sales Channel

		annotation SummarizationSetBy = Automatic

	column 'Close Date/Expected Close Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5d1ce7b4-2d13-455f-86ff-dd2b4de4e230
		summarizeBy: none
		sourceColumn: Close Date/Expected Close Date

		variation Variation
			isDefault
			relationship: b3173a69-7e54-47d1-9d44-dc6e81e5473a
			defaultHierarchy: LocalDateTable_204ddefd-6c29-4a0a-ba88-1d7f5c5ba71b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Next Steps'
		dataType: string
		lineageTag: b92b626e-a75f-4c3b-972d-e8b9327eb75b
		summarizeBy: none
		sourceColumn: Next Steps

		annotation SummarizationSetBy = Automatic

	column Images
		dataType: string
		lineageTag: 1e8c2e1f-f4a9-4fde-aef6-e73c681711c6
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Images

		annotation SummarizationSetBy = Automatic

	column 'Deal Status' =
			
			SWITCH(TRUE(),'Sales Opportunities'[Sales stage]="Won", "Won", 'Sales Opportunities'[Sales stage]="Lost", "Lost", "Open")
		lineageTag: 2e5ffb67-55ce-4717-99e9-e68735d3d67d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sales Opportunities' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Utente\Downloads\Sales Opportunities.xlsx"), null, true),
				    #"Sales Opportunities_Sheet" = Source{[Item="Sales Opportunities",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Sales Opportunities_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Opportunity ID", type text}, {"Reporting Date", type date}, {"Salesperson", type text}, {"Customer", type text}, {"Country", type text}, {"Sales stage", type text}, {"Opportunity Value (USD)", Int64.Type}, {"Sales Channel", type text}, {"Close Date/Expected Close Date", type date}, {"Next Steps", type text}, {"Column11", type any}, {"Column12", type any}, {"Column13", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Reporting Date", "Salesperson", "Customer", "Country", "Sales stage", "Opportunity ID", "Opportunity Value (USD)", "Sales Channel", "Close Date/Expected Close Date", "Next Steps"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Other Columns","US","United States",Replacer.ReplaceText,{"Country"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Replaced Value",{"Reporting Date", "Country", "Salesperson", "Customer", "Sales stage", "Opportunity ID", "Opportunity Value (USD)", "Sales Channel", "Close Date/Expected Close Date", "Next Steps"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Reordered Columns","UK","United Kingdom",Replacer.ReplaceText,{"Country"}),
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value1", {"Salesperson"}, Salesperson, {"Salesperson"}, "Salesperson.1", JoinKind.LeftOuter),
				    #"Expanded Salesperson.1" = Table.ExpandTableColumn(#"Merged Queries", "Salesperson.1", {"Images"}, {"Images"})
				in
				    #"Expanded Salesperson.1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

